name: app_environment
channels:
  - snowflake
dependencies:
  - python=3.11.*
  - snowflake-snowpark-python=
  - streamlit=
  - pandas=
  - numpy=
  - plotly=
  - pyyaml=
  - scipy=
  - scikit-learn=
  - openpyxl=
